### PR TITLE
Postgres sql backend

### PR DESCRIPTION
**Pull request by henrik-muehe**
Initial implementation of a postgres backend. Tried simple queries which do work for me. This would help resolve https://github.com/paulasmuth/fnordmetric/issues/221.

### CODE REVIEW

**Comment by paulasmuth** [comment]
Wow, this looks great! :)

**Comment by paulasmuth** [comment]
:beers:

**Comment by ermolaev** [comment]
Hello, Initial implementation of a postgres backend - good news!

but now I have next error (libpq-dev is installed), ubuntu 14.04
```
-- Could NOT find PostgreSQL (missing:  PostgreSQL_TYPE_INCLUDE_DIR) (found version "9.4.1")
WARNING: libpq not found, FnordMetric will be compiled without Postgres support
```
```
ls /usr/include/postgresql         
9.4  internal  libpq  libpq-events.h  libpq-fe.h  pg_config_ext.h  pg_config.h  pg_config_manual.h  pg_config_os.h  postgres_ext.h
```

**Comment by henrik-muehe** [comment]
This might be an issue with the cmake postgres library discovery. I'll look into that.

**Comment by rsivapr** [comment]
Awesome stuff. :beers: @henrik-muehe

**Pull request merged**
